surface_detection:
  frame_id: "world_frame"
  k_search: 50
  meanK: 50
  stdv_threshold: 1
  rg_min_cluster_size: 100
  rg_max_cluster_size: 100000
  rg_neightbors: 50
  rg_smoothness_threshold: 0.12217304763960307
  rg_curvature_threshold: 1.0
  tr_search_radius: 0.01
  tr_mu: 2.5
  tr_max_nearest_neighbors: 100
  tr_max_surface_angle: 0.7853981633974483
  tr_min_angle: 0.17453292519943295
  tr_max_angle: 2.0943951023931953
  tr_normal_consistency: False
  voxel_leafsize: 0.01
  marker_alpha: 1
  ignore_largest_cluster: False
  occupancy_threshold: 0.1
  mls_upsampling_radius: 0.01
  mls_point_density: 40
  mls_search_radius: 0.01
  use_tabletop_seg:  True
  tabletop_seg_distance_threshold: 0.005

  use_octomap: False
  occupancy_threshold: 0.5
