surface_detection:
  frame_id: world_frame
  k_search: 50
  marker_alpha: 0.6

  stout_mean: 50
  stout_stdev_threshold: 1.0

  rg_min_cluster_size: 100
  rg_max_cluster_size: 10000
  rg_neighbors: 100
  rg_smoothness_threshold: 0.034
  rg_curvature_threshold: 1.0

  pa_enabled: true
  pa_seg_max_iterations: 100
  pa_seg_dist_threshold: 0.008
  pa_sac_plane_distance: 0.008
  pa_kdtree_radius: 0.008

  tr_search_radius: 0.03
  tr_mu: 100
  tr_nearest_neighbors: 200
  tr_max_surface_angle: 1.047
  tr_min_angle: 0.36
  tr_max_angle: 2.61
  tr_normal_consistency: false

  voxel_leaf: 0.008
  use_tabletop_segmentation: true
  tabletop_seg_distance_thresh: 0.02
  ignore_largest_cluster: false
  occupancy_threshold: 0.5

  mls_upsampling_radius: 0.08
  mls_point_density: 100
  mls_search_radius: 0.08

